name = "LightweightStats"
uuid = "6e4b0b68-1f2b-4a7e-8f0e-d3e9f3d5c8a1"
version = "1.0.0"
authors = ["ChrisRackauckas <contact@chrisrackauckas.com>"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
ExplicitImports = "1.14.0"
JET = "0.9, 0.10, 0.11"
PrecompileTools = "1"
julia = "1.10"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ExplicitImports", "JET", "Random", "Statistics", "Test"]
