name = "LightweightStats"
uuid = "6e4b0b68-1f2b-4a7e-8f0e-d3e9f3d5c8a1"
version = "1.0.0"
authors = ["ChrisRackauckas <contact@chrisrackauckas.com>"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
AllocCheck = "0.1, 0.2"
PrecompileTools = "1"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AllocCheck", "Test", "Random", "Statistics"]
